### ISSUE TITLE
Add satellite / aerial map to www as alternative

### ISSUE THREAD

**Issue by klokan** [webglearth/www.webglearth.com#3]
We should create keys on Bing and Mapbox - and show them as alternative maps in the dropdown.

The keys should be specific for www.webglearth.com website - and not to be used elsewhere. 

Default map should remain to be KlokanTech Streets.

**Comment by petrsloup** [comment]
We will use Klokantech Hybrid from TileHosting.com for this, together with updating the geocoder.

**Comment by klokan** [comment]
Please set it as the default...
